### PR TITLE
Mapping corrections and new builder component

### PR DESCRIPTION
**Pull request by domstoppable**
Fixes errors in mapping calculations from non-pix spatial units

### CODE REVIEW

**Comment by domstoppable** [comment]
@mdcutone @TEParsons - we would love to get the merged in and pypi updated with these changes

**Comment by peircej** [comment]
> @mdcutone @TEParsons - we would love to get the merged in and pypi updated with these changes

Hi @domstoppable I'm happy to pull this in when the tests pass (I noticed yesterday they failed) but it looks like they've progressed past yesterday's fail today (at least on linux)

**Comment by peircej** [comment]
Oh, the reason the tests are failing to find a runner on MacOS is that they're set to use `macos-11` in the Github workflow. That's deprecated and needs moving to `macos-13`. `macos-latest` uses ARM architecture so probably best to avoid that for now.

**Comment by domstoppable** [comment]
Good call, @peircej - look ok now?

**Comment by peircej** [comment]
OK, great. So, to publish we need to:
- [x] update the version number in pyproject. Is this a pure bug-fix 0.2.2 or adds functionality 0.3.0? Or maybe we think this is really out of beta mode and call it 1.0.0. I'd say @domstoppable is best to make that judgement call
- [x] add a new tag on github to initiate the build/publish action

**Comment by domstoppable** [comment]
@peircej - looks like the repo may not be configured correctly for the pypi push. See: https://github.com/psychopy/psychopy-eyetracker-pupil-labs/actions/runs/10699853938

**Pull request merged**
