### PR TITLE
RF: Implement new test/docs structure

### PR DESCRIPTION
**Pull request by TEParsons**

### CODE REVIEW

**Comment by TEParsons** [comment]
Some context for @domstoppable: The first commit is pretty standard, just adding the same tests/docs structure as our other plugins. The second is what I'm more concerned about - basically, we're working on allowing PsychoPy to detect eyetracker backends via plugin entry points rather than the hardcoded if statements we're currently using, so I'm going through all the eyetracker plugins to give them the necessary entry points. This one is a bit more complicated as you have two EyeTracker classes, so I've given them different names (otherwise they'd overwrite one another in the iohub namespace). Adding you as a reviewer to check that this is okay and hopefully won't break anything?

**Comment by TEParsons** [comment]
Pulled in so tests can run, but can change the names back if it breaks anything

**Comment by domstoppable** [comment]
Ah, yes - I remember seeing the hardcoded bits and wondering if/when that might eventually change. Sounds like a good move.

The changes look reasonable, but of course we'll want to carefully test when we can. Are the corresponding changes already in place in the PsychoPy repo so that we can try this out?

Also, since the new plugin system is now such a large departure from the old system, there's a naming change I'd like to make. Since we support two eyetrackers (Neon and Pupil Core), we needed to give them separate names. For Neon I went with "Pupil Labs (Neon)" and left Core as-is (simply "Pupil Labs") in an effort to not break existing projects. At this point though, I think it's probably better to rename the "Pupil Labs" eyetracker to "Pupil Labs (Core)".

**Comment by TEParsons** [comment]
The accompanying changes are in, yes! Only to psychopy:dev though.

When you say renaming, do you mean the labels which appear in Builder? Annoyingly we have a system to make changing those labels safely trivial, but eyetracker backends currently can't plug use it as the function to get backends only returns one set of values (not a set of values and a set of labels). I'd like to set it up so that there's just a class which you can subclass to add parameters / options (meaning you can add whatever label you like) - it would be a big change and probably a bit much for this release, but if you're happy to wait then it may become easier soon(ish) to change those labels safely

**Pull request merged**
